service:
  name: dcc-rubbish-days

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: dcc-recycling.aramsay.co.nz
    stage: production
    basePath: ''
    createRoute53Record: true
    certificateName: '*.aramsay.co.nz'
    endpointType: regional

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    CACHE_TABLE_NAME: { "Ref": "CacheTable" }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["CacheTable", "Arn" ] }

functions:
  app:
    handler: handler.express
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    CacheTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
